rope climbing robot
marsiitr/Rope-Climbing-Robot pull request #1
Opened 2020-07-27 18:58 UTC by adityatidke

2020-07-27 19:05 UTC, adityatidke commented
Please merge this .

2020-07-28 07:56 UTC, SanjeevKrishnan requested changes
@adityatidke Changes are required!
1. Folder names given in the documentation guideline has to be followed properly(with Case Sensitivity). For ex., it is "Images and Videos", not "images and videos".
2. flowchart.jpg has to be present inside Images and Videos/Images.
3. Snapshots of all CAD files have to be present inside the Mechanical Design folder.
4. Names of files have to be self-explanatory. Few files inside the Mechanical Design folder have names as "WhatsApp Images" which is not allowed.
5. CAD images have to be present inside the Mechanical Design folder, not Images and Videos/Images. All other project images related images like prototype images, flowcharts, circuit diagrams, team picture has to be present inside Images and Videos/Images.
6. Text in poster, report, and README.md has to be justified. You can justify text in README.md using HTML tags.

2020-07-29 11:21 UTC, Shubhanshu07 commented
@adityatidke Use Markdown Syntax it would be easier to add the links, images, list in the Readme file.
https://commonmark.org/help/

2020-07-29 12:54 UTC, adityatidke commented
Real image of the robot is added      
 @Shubhanshu07 sir, how can we align the text in markdown ?

2020-07-29 14:14 UTC, Shubhanshu07 commented
@adityatidke you can use p tag to align justify for each paragraph.
For list you can use markdown syntax

2020-07-29 15:25 UTC, adityatidke commented
Thank you sir . I have updated the readme according

2020-07-29 15:31 UTC, SanjeevKrishnan requested changes

2020-07-29 15:31 UTC, SanjeevKrishnan commented on readme.md
> +<h2>Abstract</h2>
@adityatidke Leave Heading while using tag. For example,
`## Abstract
<p align="justify">This Rope climbing bot is used to climb ropes in an easy and efficient manner to reduce manual labour.Motorised rollers are used for climbing and a leadscrew is used for the gripping.</p>`

2020-07-29 15:31 UTC, SanjeevKrishnan commented on readme.md
> +- <a href="https://github.com/adityatidke">Aditya Tidke</a>
Don't use HTML tags for Team Members, Mentors list, Refernce. And make it ordered list

2020-07-29 15:50 UTC, adityatidke commented
Suggestions have been implemented .

2020-07-29 16:02 UTC, Shubhanshu07 commented
@adityatidke Great work PR looks good to me 👍

2020-07-29 16:02 UTC, merged